Support Compositor running on another IP WiP
membraneframework/membrane_live_compositor_plugin pull request #211
Opened 2024-12-05 16:50 UTC by FelonEkonom

2024-12-10 12:14 UTC, wkozyra95 requested changes
all tcp_sink and tcp_source elements are still connecting to localhost

2024-12-12 12:23 UTC, wkozyra95 commented on lib/membrane/live_compositor/server_runner.ex
I can't comment on the line, but you need to handle the option you added in ensure_server_started

2024-12-13 09:03 UTC, varsill approved these changes

2024-12-17 12:51 UTC, wkozyra95 commented on lib/membrane/live_compositor/server_runner.ex
> +    with {:ok, ip} <- :inet.gethostbyname(hostname) do
https://www.erlang.org/doc/apps/kernel/inet.html#gethostbyname/2
You can force ipv4 address with Family option

2025-01-17 14:29 UTC, merged